# Generated by Django 4.2.13 on 2024-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('vote', models.BooleanField()),
            ],
            options={
                'db_table': 'voter',
            },
        ),
    ]
