# Generated by Django 4.2.13 on 2024-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name': 'Голосующий', 'verbose_name_plural': 'Голосующие'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='occupation',
            field=models.CharField(max_length=100, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote',
            field=models.BooleanField(verbose_name='Голос'),
        ),
    ]
