# Generated by Django 4.2.13 on 2024-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_candidate_options_alter_voter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateTimeField(verbose_name='Начало голосования')),
                ('finish_date', models.DateTimeField(verbose_name='Конец голосования')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосовании',
                'db_table': 'vote',
            },
        ),
    ]
