# Generated by Django 4.2.13 on 2024-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vote_finish_date_alter_vote_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Электронная почта'),
        ),
    ]
