# Generated by Django 4.2.13 on 2024-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_voter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='vote',
            field=models.BooleanField(default=False, verbose_name='Голос'),
        ),
    ]
