# Generated by Django 4.2.13 on 2024-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_voter_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Электронная почта')),
                ('public_key', models.CharField(max_length=256, verbose_name='Открытый ключ')),
            ],
            options={
                'verbose_name': 'Валидатор',
                'verbose_name_plural': 'Валидаторы',
                'db_table': 'validator',
            },
        ),
    ]
