# Generated by Django 4.2.13 on 2024-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
